routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/
#URL::forceScheme('https');//para navegar siempre por https://

Route::get('/', function () {
    return redirect()->to('home');
});

Route::get('alerta1', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta1();
});
Route::get('alerta2', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta2();
});
Route::get('alerta3', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta3();
});
Route::get('alerta4', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta4();
});
Route::get('alerta5', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta5();
});
Route::get('mensaje2', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje2();
});
Route::get('mensaje3', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje3();
});
Route::get('mensaje4', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje4();
});
Route::get('mensaje5/{id}', function ($id) {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje5($id);
});
Route::get('mensaje6/{id}', function ($id) {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje6($id);
});
Route::get('mensaje7', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje7();
});

Route::get('config',[
      'as'=>'config' ,
      'middleware' => 'auth',
      'uses' => 'ConfigController@index'
  ]);
Route::post('admin/config/update/{id}',[
      'as'=>'admin.config.update' ,
      'middleware' => 'auth',
      'uses' => 'ConfigController@update'
  ]);
Route::post('encuesta/responder',[
      'as'=>'encuesta.responder' ,
      'middleware' => 'auth',
      'uses' => 'EncController@responder'
  ]);
Route::get('push',[
      'as'=>'push' ,
      'middleware' => 'auth',
      'uses' => 'PushController@push'
  ]);

Route::get('admin/asignacion/seguimiento/{id}/edit2',[
      'as'=>'admin.asignacion.seguimiento.edit2' ,
      'middleware' => 'auth',
      'uses' => 'SegController@edit2'
  ]);

Route::post('mensaje/store',[
        'as'=>'mensaje.store' ,
        'uses' => 'MensajeController@store'
    ]);

Route::get('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);
Route::get('qrcode/create/{id}',[
        'as'=>'qrcode.create' ,
        'uses' => 'PdfController@qrcode'
    ]);

Route::post('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);

Route::post('estado_doc/{id}/{asigc_id}',[
        'as'=>'estado_doc' ,
        'uses' => 'HomeController@estado_doc'
    ]);

Route::resource('links', 'LinksController');

Auth::routes();

Route::get('codigo', function () {
    return redirect()->to('home');
});

Route::post('codigo',[
    'as'=>'codigo' ,
    'uses' => 'CodigosController@codigo_token'
]);

Route::get('/welcome',[
    'as'=>'welcome', function () { return redirect()->to('home'); }
]);

Route::post('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/admin', function () { return view('admin'); });
Route::get('/reportes', [
    'as'=>'reportes' ,
    'uses' => function () { return view('reportes.index'); }
]
);
Route::get('/reportes/buscar',[
    'as'=>'reportes.buscar' ,
    'uses' => 'PdfController@buscar'
]
);
Route::post('/reportes/buscar',[
    'as'=>'reportes.buscar.post' ,
    'uses' => 'PdfController@buscar'
]
);

Route::get('rol/{id}',[
        'as'=>'rol' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->rol = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);
Route::get('modo_escritorio/{id}',[
        'as'=>'modo_escritorio' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->modo_escritorio = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);

Route::group(['prefix' => 'admin', 'as'=>'admin.'], function () {
    Route::resources([
        'usuarios' => 'UserController'
    ]);
    Route::get('usuarios/{id}/delete',[
        'as'=>'usuarios.delete' ,
        'uses' => 'UserController@destroy'
    ]);
    Route::post('usuarios/{id}',[
        'as'=>'usuarios.update' ,
        'uses' => 'UserController@update'
    ]);
    
    
    Route::resources([
        'facultad' => 'FacController'
    ]);
    Route::get('facultad/{id}/delete',[
        'as'=>'facultad.delete' ,
        'uses' => 'FacController@destroy'
    ]);
    Route::post('facultad/{id}',[
        'as'=>'facultad.update' ,
        'uses' => 'FacController@update'
    ]);
    Route::resources([
        'periodo' => 'PeriodoController'
    ]);
    Route::get('periodo/{id}/delete',[
        'as'=>'periodo.delete' ,
        'uses' => 'PeriodoController@destroy'
    ]);
    Route::post('periodo/{id}',[
        'as'=>'periodo.update' ,
        'uses' => 'PeriodoController@update'
    ]);
    
     Route::resources([
        'departamento' => 'DeptoController'
    ]);
    Route::get('departamento/{id}/delete',[
        'as'=>'departamento.delete' ,
        'uses' => 'DeptoController@destroy'
    ]);
    Route::post('departamento/{id}',[
        'as'=>'departamento.update' ,
        'uses' => 'DeptoController@update'
    ]);
    
    Route::resources([
        'programa' => 'ProgController'
    ]);
    Route::get('programa/{id}/delete',[
        'as'=>'programa.delete' ,
        'uses' => 'ProgController@destroy'
    ]);
    Route::post('programa/{id}',[
        'as'=>'programa.update' ,
        'uses' => 'ProgController@update'
    ]);
    Route::resources([
        'asignatura' => 'AsigtController'
    ]);
    Route::get('asignatura/{id}/delete',[
        'as'=>'asignatura.delete' ,
        'uses' => 'AsigtController@destroy'
    ]);
    Route::post('asignatura/{id}',[
        'as'=>'asignatura.update' ,
        'uses' => 'AsigtController@update'
    ]);
    Route::resources([
        'contenido' => 'ContAsigtController'
    ]);
    Route::get('contenido/{id}/delete',[
        'as'=>'contenido.delete' ,
        'uses' => 'ContAsigtController@destroy',
        'middleware' => 'rol:admin'
    ]);
    Route::get('contenido/{id}/create',[
        'as'=>'contenido.create' ,
        'uses' => 'ContAsigtController@create',
        'middleware' => 'rol:admin'
    ]);
    Route::post('contenido/{id}',[
        'as'=>'contenido.update' ,
        'uses' => 'ContAsigtController@update',
        'middleware' => 'rol:admin'
    ]);
    Route::group(['prefix' => 'asignacion', 
    'as'=>'asignacion.'], function () {
        Route::resources([
            'programaciontematica' => 'ProgTemController'
        ]);
        Route::post('consultar_planes_prog',[
        'as'=>'consultar_planes_prog',
        'uses' => 'AsigcController@consultar_planes_prog'
        ]);
        Route::post('{id}/programaciontematica/update',[
        'as'=>'programaciontematica.update',
        'uses' => 'ProgTemController@update'
        ]);
          Route::group(['prefix' => 'programaciontematica', 'as'=>'programaciontematica.'], function () {
               Route::get('{id}/refebiblio/{id2}/delete',[
                'as'=>'refebiblio.delete' ,
                'uses' => 'ProgTemRefeBiblioController@destroy'
                ]);
                Route::post('{id}/refebiblio/store',[
                'as'=>'refebiblio.store' ,
                'uses' => 'ProgTemRefeBiblioController@store'
                ]);
                
               Route::get('{id}/puntoadic/{id2}/delete',[
                'as'=>'puntoadic.delete' ,
                'uses' => 'ProgTemPuntoAdicController@destroy'
                ]);
                Route::post('{id}/puntoadic/store',[
                'as'=>'puntoadic.store' ,
                'uses' => 'ProgTemPuntoAdicController@store'
                ]);
          });
        Route::resources([
            'seguimiento' => 'SegController'
        ]); 
        
    Route::post('seguimiento/{id}/edit',[
        'as'=>'seguimiento.edit' ,
        'uses' => 'SegController@edit_post'
    ]);

    
    Route::resources([
            'informefinal' => 'InfoFinController'
        ]);
    });
    Route::resources([
        'asignacion' => 'AsigcController'
    ]);
    Route::get('asignacion/{id}/delete',[
        'as'=>'asignacion.delete' ,
        'uses' => 'AsigcController@destroy'
    ]);
    Route::post('asignacion/{id}',[
        'as'=>'asignacion.update' ,
        'uses' => 'AsigcController@update'
    ]);
   Route::get('asignacion/create/individual',[
        'as'=>'asignacion.createindividual' ,
        'uses' => 'AsigcController@create_individual',
        'middleware' => 'rol:admin|director'
    ]);
   Route::get('asignacion/create/plan',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
  /*
   Route::get('asignacion/create/plan/{cod_prog}',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
*/
    Route::resources([
        'planes' => 'PlanesController'
    ]);
    Route::get('planes/{id}/delete',[
        'as'=>'planes.delete' ,
        'uses' => 'PlanesController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::post('planes/{id}',[
        'as'=>'planes.update' ,
        'uses' => 'PlanesController@update',
        'middleware' => 'rol:admin|director'
    ]);
    Route::get('planes/{id}/create',[
        'as'=>'planes.create' ,
        'uses' => 'PlanesController@create'

resources/views/reportes/css.blade.php
<style>
    table{
        text-align:center;
        width:100%;
    }
    table tr th, table tr td{
        padding:5px;
    }
    .titulo{
        text-align:center;
        font-weight:lighter !important;
    }
    .negrita{
         font-weight:bold !important;
    }
    .reporte *{
         font-family: "Humanst521 BT";
         font-weight:lighter;
    }
    #titulo_logo{
        text-align:center;
        margin:0 auto;
        font-weight:lighter !important;
    }
    #titulo_logo strong{
        font-weight:bold;   
    }
    .m10{
        font-weight:lighter;
        font-size:.9em;
    }
    .alineado_izquierda{
        text-align:left;
    }
    .borde_superior{
        border-top:1px solid black;
    }
    .borde_inferior{
        border-bottom:1px solid black;
    }
</style>

resources/views/reportes/flexibilidad.blade.php
@extends('layouts.app')
@section('vars')
{!!
$facultad = "Ciencias Exactas y Naturales";
$programa = "Licenciatura en Informática";
$facultad = mb_strtoupper($facultad,'utf-8');
$programa = mb_strtoupper($programa,'utf-8');
$page_title = "IDENTIFICACI&Oacute;N DE LOS PROGRAMAS A LOS CUALES SE OFRECE";
!!}
@endsection
@section('style')
<style>
  table tr th, table tr td {
    text-align: center;
}
</style>
@endsection
@section('barra_buscar')
<li><a onclick="window.print()" title="Imprimir">
<span class="glyphicon glyphicon-print"></span>
</a></li>
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> Flexibilidad</li>
</ol>
@endsection
@section('scripts')
@include('reportes.css')
@endsection
@section('content')
<center><strong><p>{{ $page_title }}</p></strong></center>
<div class='row'>
  <div class='col-md-12'>
    <table border="1">
      <thead>
      <tr>
        <th colspan="2">Asignatura</th>
        <th>Programa</th>
        <th>Periodo de Ingreso</th>
        <!--th>Periodo acadmico</th-->
      </tr>
    </thead>
    <body>
  @foreach ($asigc as $asigt_i)
    <!--
      <div class="panel panel-default" style="width: 24rem;display:inline-block">
  <div class="panel-body">
    <h5 class="card-title">{{ $asigt_i->nom_asigt }}</h5>
    @if ($asigt_i->flex == 'SI')
    <span class="badge badge-success">Flexibilidad</span>
    @endif
    <h6 class="card-title">
    Docente: ({{ $asigt_i->ident_docnt }}) {{ $asigt_i->name }}
    </h6>
    <p class="card-text">{{ $asigt_i->obj_gen }}</p>
    <!--a href="#" class="btn btn-primary">Go somewhere</a- ->
<nav class="navbar navbar-default">
  <div class="container-fluid">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling - ->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
            <li><a href="{{ route('reportes.prog_tem',$asigt_i->id) }}">Programación Temática</a></li>
            <li><a href="#">Seguimiento</a></li>
            <li><a href="#">Informe Final</a></li>
      </ul>
    </div><!-- /.navbar-collapse - ->
  </div><!-- /.container-fluid - ->
</nav>
</div>
</div>
-->
<tr>
  <td>{{ $asigt_i->cod_asigt }}</td>
  <td><a href="{{ route('admin.asignatura.show',[$asigt_i->asigt_id]) }}">{{ $asigt_i->nom_asigt }}</a></td>
  <td>{{ $asigt_i->prog->nom_prog }}</td>
  <td>{{ $asigt_i->prog->periodo_ingreso }}</td>
  <!--td>{{ $asigt_i->per_acad}}</td-->
</tr>
@endforeach
</body>
</table>
  </div>
</div>

@endsection

resources/views/reportes/index.blade.php
@extends('layouts.app')

@section('style')
<style>
.adminmenu li a{
    color: #000000 !important;
    font-weight: bold !important;
}
</style>
@endsection
@section('ruta_de_migas')
<nav class="navbar navbar-default">
<ol class="breadcrumb navbar-left">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> Reportes</li>
</ol>
<div class="collapse navbar-collapse" id="app-navbar-collapse">
</nav>
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-xs-12">
            
<span>
<!--
reportes.buscar.12324
<meta name="csrf-token" content="{{ csrf_token() }}">
<input type="hidden" name="_token" value="{{ csrf_token() }}">
-->
<form nethod="post" action="{{ route('reportes.buscar.post') }}">
 <label for="codigo">Verificar Docuento. <i style="color:gray">Escriba el código para comprobar su documento</i></label>
        <div class="input-group">
            <span class="input-group-addon" data-toggle="modal" data-target="#lectorQR"><i class="glyphicon glyphicon-qrcode"></i></span>
            <input autocomplete="off" type="text" id="codigo" name="codigo" value="" class="form-control" required aria-label="Escriba el número de comprobante en su ticket">
            <span class="input-group-addon">
                <button type="submit">
                <i class="glyphicon glyphicon-search"></i>
                </button>
                </span>
        </div>
</span>
</form>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="lectorQR" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Lector QR</h4>
      </div>
      <div class="modal-body">
        
     <div class="col-md-12">
            <label><input type="checkbox" checked id="vibrar">Vibrar</label>
            <span id="log"></span>
            <div class="card">
                <div class="card-header"><span id="aviso">Listo para leer</span><br>
                <span id="actual" class="float-left" style="
    color: red;
    font-size: 24px;
    font-weight: bold;
"></span>
                
                <span id="total" class="float-right" style="
    color: red;
    font-size: 24px;
    font-weight: bold;
"></span>
                </div>

                <div class="card-body" style = "text-align: center;">
                    <video style="position: relative;width: 100%;transform: scaleX(-1);" muted playsinline id="qr-video"></video>
                </div>
                <div class="card-footer">
                    <select class="form-control" id="inversion-mode-select">
                    <option value="both">Scan both</option>
                    <option value="original">Scan original (dark QR code on bright background)</option>
                    <option value="invert">Scan with inverted colors (bright QR code on dark background)</option>
                    </select>
                    <b>Detected QR code: </b>
<span id="cam-qr-result">None</span>
<b>Last detected at: </b>
<span id="cam-qr-result-timestamp"></span>
<span style="display:none;">
    
<h1>Scan from File:</h1>
<input type="file" id="file-selector">
<b>Detected QR code: </b>
<span id="file-qr-result">None</span>
</span>
                </div>
            </div>
        </div><!--fin contetn-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script type="module">
    import QrScanner from "{{ secure_asset('lib/qr-scanner/qr-scanner.min.js')}}";
    QrScanner.WORKER_PATH = "{{ secure_asset('lib/qr-scanner/qr-scanner-worker.min.js')}}";

    const video = document.getElementById('qr-video');
    const camHasCamera = document.getElementById('cam-has-camera');
    const camQrResult = document.getElementById('cam-qr-result');
    const camQrResultTimestamp = document.getElementById('cam-qr-result-timestamp');
    const fileSelector = document.getElementById('file-selector');
    const fileQrResult = document.getElementById('file-qr-result');
    const aviso = document.getElementById('aviso');
    function setResult(label, result) {
        if (typeof old_result !== 'undefined') var old_result = '';
        //window.open(result);
        label.textContent = result;
        camQrResultTimestamp.textContent = new Date().toString();
        label.style.color = 'teal';
        clearTimeout(label.highlightTimeout);
        label.highlightTimeout = setTimeout(() => label.style.color = 'inherit', 100);
        if (old_result!=result)
        document.location.href = result;
        old_result = result;
    }
    
    if (typeof window.result_viejo === 'undefined') window.result_viejo = '';
    function setResult2(camQrResult, result){
        if (window.result_viejo != result){
            setResult(camQrResult, result);
            result_viejo = result;
        }
    }

    // ####### Web Cam Scanning #######
    QrScanner.hasCamera().then(hasCamera => camHasCamera.textContent = hasCamera);

    const scanner = new QrScanner(video, result => setResult2(camQrResult, result));
    scanner.start();

    document.getElementById('inversion-mode-select').addEventListener('change', event => {
        scanner.setInversionMode(event.target.value);
    });

    // ####### File Scanning #######

    fileSelector.addEventListener('change', event => {
        const file = fileSelector.files[0];
        if (!file) {
            return;
        }
        QrScanner.scanImage(file)
            .then(result => setResult(fileQrResult, result))
            .catch(e => setResult(fileQrResult, e || 'No QR code found.'));
    });
function vibrar(){
    var vibrar = document.getElementById('vibrar');
    if (vibrar.checked){
        
        if (window.navigator && window.navigator.vibrate) { 
            try {
                  // En caso de ser compatible 
                    navigator.vibrate (0);
                    navigator.vibrate (1000); 
                }
                catch(error) {
                   vibrar.click();
                }
                            
        } else { 
            vibrar.click();
            // En caso de no ser compatible 
            console.log('Tu dispositivo no soporta la API de vibración');
        }
    }
}
</script>
  
<style>
     canvas {
        display: none;
    }
    hr {
        margin-top: 32px;
    }
    input[type="file"] {
        display: block;
        margin-bottom: 16px;
    }
    div {
        margin-bottom: 16px;
    }
</style>
@endsection

resources/views/reportes/inf_final.blade.php
@extends('layouts.app')
@section('vars')
{!!
$facultad = mb_strtoupper($facultad,'utf-8');
$programa = mb_strtoupper($programa,'utf-8');

!!}
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> Informe Final</li>
</ol>
@endsection
@section('barra_buscar')
<li><a onclick="window.print()" title="Imprimir">
<span class="glyphicon glyphicon-print">
</a></li>
@endsection
@section('scripts')
@include('reportes.css')
@endsection
@section('content')
@include('reportes.partials.inf_final')
  @endsection

resources/views/reportes/planes.blade.php
@extends('layouts.app')
@section('vars')
<?php
$page_title = 'Planes'; 
?>
@endsection

@section('barra_buscar_cuerpo')
<nav class="navbar navbar-default">

<div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
<ul class="nav navbar-nav navbar-right">
    <li><a style="margin: 0; padding: 8px;">
    <div class="input-group sidebar-form">
      <label for="buscar">Seleccione un programa&nbsp;</label>
    <select style="background-color: #FFF;color:black;width:170px;display:inline" id="buscar" class="js-example-basic-single form-control">
      @foreach ($prog as $id => $prog_i)
      <option @if($prog_i->cod_prog=="011") selected @endif value="{{$prog_i->cod_prog}}">{{$prog_i->nom_prog}}</option>
      @endforeach
    </select>
    </div>
    </a></li>
    <li>
          <span class="input-group-btn" style="display:inline">
          <input title="Número de resultados" class="form-control" style="    height: 27px;
    margin-top: 9px;background-color: rgb(255, 255, 255);color: black;width: 70px;border-bottom: 1px none transparent;border-left: 0px solid black;margin-right: 1px;border-right: 1px solid #ccd0d2;border-bottom: 1px solid #ccd0d2;" min="1" id="num_resultados"  type="number" value="3" solonumeros>
          </span>
    </li>
</ul>
</div>
</nav>
@endsection
@section('scripts')
<script>
$(document).ready(function(){
$("#buscar").keyup(function(){
  buscar_planes();
});
$("#buscar").change(function(){
  buscar_planes();
});
$("#search-btn").click(function(){
  buscar_planes();
});
$("#num_resultados").keyup(function(){
  buscar_planes();
});
$("#num_resultados").change(function(){
  buscar_planes();
});
$("#menu_planes").addClass('active');
buscar_planes();
});
</script>
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home')}}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active"><i class="fa fa-user"></i> {{ $page_title }}</li>
</ol>
@endsection
@section('content')
<center><h1>{{ $page_title }}</h1></center>
@if($botones)
<input type="hidden" id="a5d546a503db8d" value="{{ $botones ? __('true') : __('false') }}">
@endif
<div class='row'>
  <div class='col-md-12'>
  <span id="txt_resultados">
</span>
 <div id="area_pagination"></div>
    
    
  </div><!-- /.col -->
  <div class='col-md-6'>

  </div><!-- /.col -->

</div><!-- /.row -->
@endsection