routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
#URL::forceScheme('https');//para navegar siempre por https://

Route::get('/', function () {
    return redirect()->to('home');
});

Route::get('alerta1', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta1();
});
Route::get('alerta2', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta2();
});
Route::get('alerta3', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta3();
});
Route::get('alerta4', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta4();
});
Route::get('alerta5', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->alerta5();
});
Route::get('mensaje2', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje2();
});
Route::get('mensaje3', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje3();
});
Route::get('mensaje4', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje4();
});
Route::get('mensaje5/{id}', function ($id) {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje5($id);
});
Route::get('mensaje6/{id}', function ($id) {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje6($id);
});
Route::get('mensaje7', function () {
  $email = new App\Http\Controllers\EmailController();
  $email->mensaje7();
});

Route::get('config',[
      'as'=>'config' ,
      'middleware' => 'auth',
      'uses' => 'ConfigController@index'
  ]);
Route::post('admin/config/update/{id}',[
      'as'=>'admin.config.update' ,
      'middleware' => 'auth',
      'uses' => 'ConfigController@update'
  ]);
Route::post('encuesta/responder',[
      'as'=>'encuesta.responder' ,
      'middleware' => 'auth',
      'uses' => 'EncController@responder'
  ]);
Route::get('push',[
      'as'=>'push' ,
      'middleware' => 'auth',
      'uses' => 'PushController@push'
  ]);

Route::get('admin/asignacion/seguimiento/{id}/edit2',[
      'as'=>'admin.asignacion.seguimiento.edit2' ,
      'middleware' => 'auth',
      'uses' => 'SegController@edit2'
  ]);

Route::post('mensaje/store',[
        'as'=>'mensaje.store' ,
        'uses' => 'MensajeController@store'
    ]);

Route::get('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);
Route::get('qrcode/create/{id}',[
        'as'=>'qrcode.create' ,
        'uses' => 'PdfController@qrcode'
    ]);

Route::post('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);

Route::post('estado_doc/{id}/{asigc_id}',[
        'as'=>'estado_doc' ,
        'uses' => 'HomeController@estado_doc'
    ]);

Route::resource('links', 'LinksController');

Auth::routes();

Route::get('codigo', function () {
    return redirect()->to('home');
});

Route::post('codigo',[
    'as'=>'codigo' ,
    'uses' => 'CodigosController@codigo_token'
]);

Route::get('/welcome',[
    'as'=>'welcome', function () { return redirect()->to('home'); }
]);

Route::post('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/admin', function () { return view('admin'); });
Route::get('/reportes', [
    'as'=>'reportes' ,
    'uses' => function () { return view('reportes.index'); }
]
);
Route::get('/reportes/buscar',[
    'as'=>'reportes.buscar' ,
    'uses' => 'PdfController@buscar'
]
);
Route::post('/reportes/buscar',[
    'as'=>'reportes.buscar.post' ,
    'uses' => 'PdfController@buscar'
]
);

Route::get('rol/{id}',[
        'as'=>'rol' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->rol = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);
Route::get('modo_escritorio/{id}',[
        'as'=>'modo_escritorio' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->modo_escritorio = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);

Route::group(['prefix' => 'admin', 'as'=>'admin.'], function () {
    Route::resources([
        'usuarios' => 'UserController'
    ]);
    Route::get('usuarios/{id}/delete',[
        'as'=>'usuarios.delete' ,
        'uses' => 'UserController@destroy'
    ]);
    Route::post('usuarios/{id}',[
        'as'=>'usuarios.update' ,
        'uses' => 'UserController@update'
    ]);
    
    
    Route::resources([
        'facultad' => 'FacController'
    ]);
    Route::get('facultad/{id}/delete',[
        'as'=>'facultad.delete' ,
        'uses' => 'FacController@destroy'
    ]);
    Route::post('facultad/{id}',[
        'as'=>'facultad.update' ,
        'uses' => 'FacController@update'
    ]);
    Route::resources([
        'periodo' => 'PeriodoController'
    ]);
    Route::get('periodo/{id}/delete',[
        'as'=>'periodo.delete' ,
        'uses' => 'PeriodoController@destroy'
    ]);
    Route::post('periodo/{id}',[
        'as'=>'periodo.update' ,
        'uses' => 'PeriodoController@update'
    ]);
    
     Route::resources([
        'departamento' => 'DeptoController'
    ]);
    Route::get('departamento/{id}/delete',[
        'as'=>'departamento.delete' ,
        'uses' => 'DeptoController@destroy'
    ]);
    Route::post('departamento/{id}',[
        'as'=>'departamento.update' ,
        'uses' => 'DeptoController@update'
    ]);
    
    Route::resources([
        'programa' => 'ProgController'
    ]);
    Route::get('programa/{id}/delete',[
        'as'=>'programa.delete' ,
        'uses' => 'ProgController@destroy'
    ]);
    Route::post('programa/{id}',[
        'as'=>'programa.update' ,
        'uses' => 'ProgController@update'
    ]);
    Route::resources([
        'asignatura' => 'AsigtController'
    ]);
    Route::get('asignatura/{id}/delete',[
        'as'=>'asignatura.delete' ,
        'uses' => 'AsigtController@destroy'
    ]);
    Route::post('asignatura/{id}',[
        'as'=>'asignatura.update' ,
        'uses' => 'AsigtController@update'
    ]);
    Route::resources([
        'contenido' => 'ContAsigtController'
    ]);
    Route::get('contenido/{id}/delete',[
        'as'=>'contenido.delete' ,
        'uses' => 'ContAsigtController@destroy',
        'middleware' => 'rol:admin'
    ]);
    Route::get('contenido/{id}/create',[
        'as'=>'contenido.create' ,
        'uses' => 'ContAsigtController@create',
        'middleware' => 'rol:admin'
    ]);
    Route::post('contenido/{id}',[
        'as'=>'contenido.update' ,
        'uses' => 'ContAsigtController@update',
        'middleware' => 'rol:admin'
    ]);
    Route::group(['prefix' => 'asignacion', 
    'as'=>'asignacion.'], function () {
        Route::resources([
            'programaciontematica' => 'ProgTemController'
        ]);
        Route::post('consultar_planes_prog',[
        'as'=>'consultar_planes_prog',
        'uses' => 'AsigcController@consultar_planes_prog'
        ]);
        Route::post('{id}/programaciontematica/update',[
        'as'=>'programaciontematica.update',
        'uses' => 'ProgTemController@update'
        ]);
          Route::group(['prefix' => 'programaciontematica', 'as'=>'programaciontematica.'], function () {
               Route::get('{id}/refebiblio/{id2}/delete',[
                'as'=>'refebiblio.delete' ,
                'uses' => 'ProgTemRefeBiblioController@destroy'
                ]);
                Route::post('{id}/refebiblio/store',[
                'as'=>'refebiblio.store' ,
                'uses' => 'ProgTemRefeBiblioController@store'
                ]);
                
               Route::get('{id}/puntoadic/{id2}/delete',[
                'as'=>'puntoadic.delete' ,
                'uses' => 'ProgTemPuntoAdicController@destroy'
                ]);
                Route::post('{id}/puntoadic/store',[
                'as'=>'puntoadic.store' ,
                'uses' => 'ProgTemPuntoAdicController@store'
                ]);
          });
        Route::resources([
            'seguimiento' => 'SegController'
        ]); 
        
    Route::post('seguimiento/{id}/edit',[
        'as'=>'seguimiento.edit' ,
        'uses' => 'SegController@edit_post'
    ]);

    
    Route::resources([
            'informefinal' => 'InfoFinController'
        ]);
    });
    Route::resources([
        'asignacion' => 'AsigcController'
    ]);
    Route::get('asignacion/{id}/delete',[
        'as'=>'asignacion.delete' ,
        'uses' => 'AsigcController@destroy'
    ]);
    Route::post('asignacion/{id}',[
        'as'=>'asignacion.update' ,
        'uses' => 'AsigcController@update'
    ]);
   Route::get('asignacion/create/individual',[
        'as'=>'asignacion.createindividual' ,
        'uses' => 'AsigcController@create_individual',
        'middleware' => 'rol:admin|director'
    ]);
   Route::get('asignacion/create/plan',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
  /*
   Route::get('asignacion/create/plan/{cod_prog}',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
*/
    Route::resources([
        'planes' => 'PlanesController'
    ]);
    Route::get('planes/{id}/delete',[
        'as'=>'planes.delete' ,
        'uses' => 'PlanesController@destroy',

app/Config.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Config extends Model
{
    public $timestamps = false;
    protected $table = 'config';
    protected $fillable = [
         'cambiar_rol', 'autorregistro', 'limpiar_cache', 'notificar_email', 'hora_notificacion'
    ];
    public $fillcolumn = [
          'cambiar_rol' => 'cambiar_rol' ,
          'autorregistro' => 'autorregistro' ,
          'limpiar_cache' => 'limpiar_cache' ,
          'notificar_email' => 'notificar_email' ,
          'hora_notificacion' => 'hora_notificacion'
    ];
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;


use App\Codigos;
use App\Config;
use Illuminate\Http\Request;
use App\User;
use Auth;
class ConfigController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');//auth|guest
        $this->middleware('rol:admin');//admin|docente|estudiante
    }
    public function index()
    {
      $config = Config::find(1);
     return view('admin.config.show')->with(['config'=>$config]);
    //dd('codigos');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
   
    public function update(Request $request, $id)
    {
      $config = Config::find(1);
      $config->hora_notificacion = $request->hora_notificacion;
      $config->save();
      return redirect()->back();
      //dd($request->hora_notificacion);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Codigos  $codigos
     * @return \Illuminate\Http\Response
     */
   
}

resources/views/admin/config/show.blade.php
@extends('layouts.app')
@section('vars')
{!! $page_title = 'Configuración'; 
!!}
@endsection
@section('scripts')
@section('barra_buscar_cuerpo')
<nav class="navbar navbar-default">
<ol class="breadcrumb navbar-left">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> {{ $page_title }}</li>
</ol>
<div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
<ul class="nav navbar-nav navbar-right">
   
</ul>
</nav>
@endsection
<script>

</script>
@endsection
@section('ruta_de_migas')
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><center><h1>{{ $page_title }}</h1></center></div>

                <div class="card-body">
                    <form method="POST" id="admin_config_update" action="{{ route('admin.config.update',[$config->id]) }}">
                       <meta name="csrf-token" content="{{ csrf_token() }}">
                       <input type="hidden" name="_token" value="{{ csrf_token() }}">
                       <input type="hidden" name="config_id" value="{{ $config->id }}">

                        <!--div class="form-group row">
                            
                            <div class="col-md-6">
                               <input name="notificar_email" type="checkbox" value="{{$config->notificar_email}}" class="form-control-checkbox {{ $errors->has('notificar_email') ? ' is-invalid' : '' }}" placeholder="Enviar notificaciones a email."><label for="notificar_email" class="col-md-4 col-form-label text-md-right">
                              {{ __('Enviar notificaciones a email.') }}
                          </label>

                                @if ($errors->has('notificar_email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('notificar_email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div-->
@php
$hora = (string)date("G:i", strtotime($config->hora_notificacion));
//var_dump($hora);
@endphp
                        <div class="form-group row">
                            <label for="hora_notificacion" class="col-md-4 col-form-label text-md-right">
                              {{ __('Hora de Notificación') }} 
                          </label>
                            <div class="col-md-6">
                               <input name="hora_notificacion" type="time" min="00:00" max="23:59" value="{{$config->hora_notificacion}}" class="form-control{{ $errors->has('hora_notificacion') ? ' is-invalid' : '' }}" placeholder="Hora de Notificación" required>

                                @if ($errors->has('hora_notificacion'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('hora_notificacion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                     
    
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                              <a href="{{ route('admin.asignatura.index') }}" class="btn btn-secondary hidden-print">Regresar</a>
<input type="submit" name="submit" value="Modificar" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection