routes/web.php
      'uses' => 'PushController@push'
  ]);

Route::get('admin/asignacion/seguimiento/{id}/edit2',[
      'as'=>'admin.asignacion.seguimiento.edit2' ,
      'middleware' => 'auth',
      'uses' => 'SegController@edit2'
  ]);

Route::post('mensaje/store',[
        'as'=>'mensaje.store' ,
        'uses' => 'MensajeController@store'
    ]);

Route::get('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);
Route::get('qrcode/create/{id}',[
        'as'=>'qrcode.create' ,
        'uses' => 'PdfController@qrcode'
    ]);

Route::post('mensaje/show/{id}',[
        'as'=>'mensaje.show' ,
        'uses' => 'MensajeController@show'
    ]);

Route::post('estado_doc/{id}/{asigc_id}',[
        'as'=>'estado_doc' ,
        'uses' => 'HomeController@estado_doc'
    ]);

Route::resource('links', 'LinksController');

Auth::routes();

Route::get('codigo', function () {
    return redirect()->to('home');
});

Route::post('codigo',[
    'as'=>'codigo' ,
    'uses' => 'CodigosController@codigo_token'
]);

Route::get('/welcome',[
    'as'=>'welcome', function () { return redirect()->to('home'); }
]);

Route::post('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/home',[
    'as'=>'home' ,
    'uses' => 'HomeController@index'
]);

Route::get('/admin', function () { return view('admin'); });
Route::get('/reportes', [
    'as'=>'reportes' ,
    'uses' => function () { return view('reportes.index'); }
]
);
Route::get('/reportes/buscar',[
    'as'=>'reportes.buscar' ,
    'uses' => 'PdfController@buscar'
]
);
Route::post('/reportes/buscar',[
    'as'=>'reportes.buscar.post' ,
    'uses' => 'PdfController@buscar'
]
);

Route::get('rol/{id}',[
        'as'=>'rol' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->rol = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);
Route::get('modo_escritorio/{id}',[
        'as'=>'modo_escritorio' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->modo_escritorio = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);

Route::group(['prefix' => 'admin', 'as'=>'admin.'], function () {
    Route::resources([
        'usuarios' => 'UserController'
    ]);
    Route::get('usuarios/{id}/delete',[
        'as'=>'usuarios.delete' ,
        'uses' => 'UserController@destroy'
    ]);
    Route::post('usuarios/{id}',[
        'as'=>'usuarios.update' ,
        'uses' => 'UserController@update'
    ]);
    
    
    Route::resources([
        'facultad' => 'FacController'
    ]);
    Route::get('facultad/{id}/delete',[
        'as'=>'facultad.delete' ,
        'uses' => 'FacController@destroy'
    ]);
    Route::post('facultad/{id}',[
        'as'=>'facultad.update' ,
        'uses' => 'FacController@update'
    ]);
    Route::resources([
        'periodo' => 'PeriodoController'
    ]);
    Route::get('periodo/{id}/delete',[
        'as'=>'periodo.delete' ,
        'uses' => 'PeriodoController@destroy'
    ]);
    Route::post('periodo/{id}',[
        'as'=>'periodo.update' ,
        'uses' => 'PeriodoController@update'
    ]);
    
     Route::resources([
        'departamento' => 'DeptoController'
    ]);
    Route::get('departamento/{id}/delete',[
        'as'=>'departamento.delete' ,
        'uses' => 'DeptoController@destroy'
    ]);
    Route::post('departamento/{id}',[
        'as'=>'departamento.update' ,
        'uses' => 'DeptoController@update'
    ]);
    
    Route::resources([
        'programa' => 'ProgController'
    ]);
    Route::get('programa/{id}/delete',[
        'as'=>'programa.delete' ,
        'uses' => 'ProgController@destroy'
    ]);
    Route::post('programa/{id}',[
        'as'=>'programa.update' ,
        'uses' => 'ProgController@update'
    ]);
    Route::resources([
        'asignatura' => 'AsigtController'
    ]);
    Route::get('asignatura/{id}/delete',[
        'as'=>'asignatura.delete' ,
        'uses' => 'AsigtController@destroy'
    ]);
    Route::post('asignatura/{id}',[
        'as'=>'asignatura.update' ,
        'uses' => 'AsigtController@update'
    ]);
    Route::resources([
        'contenido' => 'ContAsigtController'
    ]);
    Route::get('contenido/{id}/delete',[
        'as'=>'contenido.delete' ,
        'uses' => 'ContAsigtController@destroy',
        'middleware' => 'rol:admin'
    ]);
    Route::get('contenido/{id}/create',[
        'as'=>'contenido.create' ,
        'uses' => 'ContAsigtController@create',
        'middleware' => 'rol:admin'
    ]);
    Route::post('contenido/{id}',[
        'as'=>'contenido.update' ,
        'uses' => 'ContAsigtController@update',
        'middleware' => 'rol:admin'
    ]);
    Route::group(['prefix' => 'asignacion', 
    'as'=>'asignacion.'], function () {
        Route::resources([
            'programaciontematica' => 'ProgTemController'
        ]);
        Route::post('consultar_planes_prog',[
        'as'=>'consultar_planes_prog',
        'uses' => 'AsigcController@consultar_planes_prog'
        ]);
        Route::post('{id}/programaciontematica/update',[
        'as'=>'programaciontematica.update',
        'uses' => 'ProgTemController@update'
        ]);
          Route::group(['prefix' => 'programaciontematica', 'as'=>'programaciontematica.'], function () {
               Route::get('{id}/refebiblio/{id2}/delete',[
                'as'=>'refebiblio.delete' ,
                'uses' => 'ProgTemRefeBiblioController@destroy'
                ]);
                Route::post('{id}/refebiblio/store',[
                'as'=>'refebiblio.store' ,
                'uses' => 'ProgTemRefeBiblioController@store'
                ]);
                
               Route::get('{id}/puntoadic/{id2}/delete',[
                'as'=>'puntoadic.delete' ,
                'uses' => 'ProgTemPuntoAdicController@destroy'
                ]);
                Route::post('{id}/puntoadic/store',[
                'as'=>'puntoadic.store' ,
                'uses' => 'ProgTemPuntoAdicController@store'
                ]);
          });
        Route::resources([
            'seguimiento' => 'SegController'
        ]); 
        
    Route::post('seguimiento/{id}/edit',[
        'as'=>'seguimiento.edit' ,
        'uses' => 'SegController@edit_post'
    ]);

    
    Route::resources([
            'informefinal' => 'InfoFinController'
        ]);
    });
    Route::resources([
        'asignacion' => 'AsigcController'
    ]);
    Route::get('asignacion/{id}/delete',[
        'as'=>'asignacion.delete' ,
        'uses' => 'AsigcController@destroy'
    ]);
    Route::post('asignacion/{id}',[
        'as'=>'asignacion.update' ,
        'uses' => 'AsigcController@update'
    ]);
   Route::get('asignacion/create/individual',[
        'as'=>'asignacion.createindividual' ,
        'uses' => 'AsigcController@create_individual',
        'middleware' => 'rol:admin|director'
    ]);
   Route::get('asignacion/create/plan',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
  /*
   Route::get('asignacion/create/plan/{cod_prog}',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
*/
    Route::resources([
        'planes' => 'PlanesController'
    ]);
    Route::get('planes/{id}/delete',[
        'as'=>'planes.delete' ,
        'uses' => 'PlanesController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::post('planes/{id}',[
        'as'=>'planes.update' ,
        'uses' => 'PlanesController@update',
        'middleware' => 'rol:admin|director'
    ]);
    Route::get('planes/{id}/create',[
        'as'=>'planes.create' ,
        'uses' => 'PlanesController@create'
    ]);
  /*
  Route::put('post/{id}', ['middleware' => 'role:editor', function ($id) {
    //
}]);
  */
  
    Route::group(['prefix' => 'planes', 
    'as'=>'planes.'], function () {
        
        /*
        Route::get('{id}/asigt/create',[
        'as'=>'asigt.create' ,
        'uses' => 'PlanesAsigtController@create',
        'middleware' => 'rol:admin'
        ]);
        */
    });
  Route::get('planesasigt/{id}/delete',[
        'as'=>'planesasigt.delete' ,
        'uses' => 'PlanesAsigtController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::resources([
          'planesasigt' => 'PlanesAsigtController'
        ]);
    Route::resources([
          'planesasigtpre' => 'PlanesPreReqController'
        ]);
   Route::get('/planesasigtpre/{planes_id}/delete/{id}',[
        'as'=>'planesasigtpre.delete' ,
        'uses' => 'PlanesPreReqController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::resources([
        'control' => 'ControlFechasController'
    ]);
    Route::get('control/{id}/delete',[
        'as'=>'control.delete' ,
        'uses' => 'ControlFechasController@destroy'
    ]);
    Route::post('control/{id}',[
        'as'=>'control.update' ,
        'uses' => 'ControlFechasController@update'
    ]);
    
    Route::resources([
        'links' => 'LinksController'
    ]);
    Route::get('links/{id}/delete',[
        'as'=>'links.delete' ,
        'uses' => 'LinksController@destroy'
    ]);
    Route::post('links/{id}',[
        'as'=>'links.update' ,
        'uses' => 'LinksController@update'
    ]);
    
    Route::resources([
        'programacion' => 'ProgTemController'
    ]);
    Route::get('programacion/{id}/delete',[
        'as'=>'programacion.delete' ,
        'uses' => 'ProgTemController@destroy'
    ]);
    Route::post('programacion/{id}',[
        'as'=>'programacion.update' ,
        'uses' => 'ProgTemController@update'
    ]);
    Route::resources([
        'seguimieto' => 'SegController'

resources/views/admin/departamento/create.blade.php
@extends('layouts.app')
@section('vars')
{!!
$page_title = 'Departamentos'; 
$route = 'departamento'; 
!!}
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li><a href="{{ route('admin.departamento.index') }}"> {{ $page_title }}</a></li>
    <li class="active"> Registrar</li>
</ol>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        password_en_formulario("admin_departamento_create");
    required_en_formulario_for("admin_departamento_create","red","*")
    });
    </script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"></div>

                <div class="card-body">
                    <form method="POST" id="admin_departamento_create" action="{{ route('admin.departamento.store') }}">
                         <meta name="csrf-token" content="{{ csrf_token() }}">
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                       <div class="form-group row">
                            <label for="id" class="col-md-4 col-form-label text-md-right">{{ __('C&oacute;digo') }}</label>

                            <div class="col-md-6">
                                <input id="id" type="number" class="form-control{{ $errors->has('id') ? ' is-invalid' : '' }}" name="id" value="{{ old('id') }}" required autofocus>

                                @if ($errors->has('id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       <div class="form-group row">
                            <label for="nom_depto" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                            <div class="col-md-6">
                                <input id="nom_depto" type="text" class="form-control{{ $errors->has('nom_depto') ? ' is-invalid' : '' }}" name="nom_depto" value="{{ old('nom_depto') }}" required autofocus>

                                @if ($errors->has('nom_depto'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('nom_depto') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
    
                        <div class="form-group row">

                            <label for="fac_id" class="col-md-4 col-form-label text-md-right">{{ __('Facultad') }}</label>
                            <div class="col-md-6">
                         
                                {!!Form::select('fac_id', $fac, 
                                ($errors->has('fac_id')) ?  old('fac_id') : ''
                                , [
                                'id' => 'fac_id',
                                'class' => 'js-example-basic-single form-control',
                                'placeholder' => 'Seleccione una Facultad',
                                'required',
                                ])!!}
                                
                                
                                @if ($errors->has('fac_id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('fac_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="director" class="col-md-4 col-form-label text-md-right">{{ __('Director') }}</label>

                            <div class="col-md-6">
                                <select id="director" class="js-example-basic-single form-control{{ $errors->has('director') ? ' is-invalid' : '' }}" name="director" required autofocus>
                                    <option value="">Seleccione un usuario</option>
                                    @foreach($usuarios as $director_i)
                                    <?php $roles = explode(",",$director_i->roles);?>
                                    @if(in_array("director",$roles))
                                    <option value="{{ $director_i->ident_usu }}"
                                    @if (old('director')==$director_i->ident_usu) {{ __(' selected ') }} 
                                    @endif;
                                    >{{ $director_i->name." (".$director_i->ident_usu.")" }}</option>
                                    @endif
                                    @endforeach
                                </select>
                                @if ($errors->has('director'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('director') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                              <a href="{{ route('admin.departamento.index') }}" class="btn btn-secondary hidden-print">Regresar</a>
                                <input type="submit" name="submit" value="Registrar" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/departamento/editar.blade.php
@extends('layouts.app')
@section('vars')
{!!
$page_title = 'Departamentos'; 
$route = 'departamento'; 
!!}
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li><a href="{{ route('admin.departamento.index') }}"> {{ $page_title }}</a></li>
    <li class="active"><i class="fa fa-plus"></i> Modificar</li>
</ol>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        password_en_formulario("admin_departamento_create");
        required_en_formulario_for("admin_departamento_create","red","*")
    });
    
    function validar_area_password(obj){
        document.getElementById('area_password').style.display = obj.checked ? 'block' : 'none';
        document.getElementById('password').value='';
        document.getElementById('password-confirm').value='';
        $('#password').prop('required',obj.checked);
        $('#password-confirm').prop('required',obj.checked);
    }
</script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"></div>

                <div class="card-body">
                    <form method="POST" id="admin_departamento_create" action="{{ route('admin.departamento.update',[
                    'id' => $depto->id,
                    ]) }}">
                        <meta name="csrf-token" content="{{ csrf_token() }}">
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="form-group row">
                            <label for="nom_depto" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                            <div class="col-md-6">
                                <input id="id" type="hidden" class="form-control{{ $errors->has('id') ? ' is-invalid' : '' }}" name="id" value="{{
                                ($errors->has('id')) ?  old('id') : $depto->id }}" required>
                                <input id="nom_depto" type="text" class="form-control{{ $errors->has('nom_depto') ? ' is-invalid' : '' }}" name="nom_depto" value="{{
                                ($errors->has('nom_depto')) ?  old('nom_depto') : $depto->nom_depto }}" required autofocus>
                                @if ($errors->has('nom_depto'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('nom_depto') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group row">

                            <label for="fac_id" class="col-md-4 col-form-label text-md-right">{{ __('Facultad') }}</label>
                            <div class="col-md-6">
                         
                                {!!Form::select('fac_id', $fac, 
                                ($errors->has('fac_id')) ?  old('fac_id') : $depto->fac_id
                                , [
                                'id' => 'fac_id',
                                'class' => 'js-example-basic-single form-control',
                                'placeholder' => 'Seleccione una Facultad',
                                'required',
                                ])!!}
                                
                                
                                @if ($errors->has('fac_id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('fac_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

<div class="form-group row">
                            <label for="director" class="col-md-4 col-form-label text-md-right">{{ __('Director') }}</label>

                            <div class="col-md-6">
                                <select id="director" class="js-example-basic-single form-control{{ $errors->has('director') ? ' is-invalid' : '' }}" name="director" required autofocus>
                                    <option value="">Seleccione un usuario</option>
                                    @foreach($usuarios as $director_i)
                                  <?php $roles = explode(",",$director_i->roles);?>
                                    @if(in_array("director",$roles))
                                    <option value="{{ $director_i->ident_usu }}"
                                     @if (count($errors)>0)
                                            @if (old('director')==$director_i->ident_usu) {{ __(' selected ') }} @endif;
                                    @else
                                        @if ($depto->director==$director_i->ident_usu) {{ __(' selected ') }} @endif;
                                    @endif;
                                    >{{ $director_i->name." (".$director_i->ident_usu.")" }}</option>
                                    @endif
                                    @endforeach
                                </select>
                                @if ($errors->has('director'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('director') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                              <a href="{{ route('admin.departamento.index') }}" class="btn btn-secondary hidden-print">Regresar</a>
                                <input type="submit" name="submit" value="Actualizar" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/departamento/index.blade.php
@extends('layouts.app')
@section('vars')
{!! $page_title = 'Departamentos'; 
!!}
@endsection
@section('barra_buscar_cuerpo')
<nav class="navbar navbar-default">
<div class="collapse navbar-collapse" id="app-navbar-collapse">
<ol class="breadcrumb navbar-left">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> {{ $page_title }}</li>
</ol>
<!-- Left Side Of Navbar -->
<ul class="nav navbar-nav navbar-right">
    @include('layouts.partials.buscar')
</ul>
</nav>
@endsection
@section('scripts')
<script>
$(document).ready(function(){
$("#buscar").keyup(function(){
  buscar_departamento();
});
$("#buscar").change(function(){
  buscar_departamento();
});
$("#search-btn").click(function(){
  buscar_departamento();
});
$("#num_resultados").keyup(function(){
  buscar_departamento();
});
$("#num_resultados").change(function(){
  buscar_departamento();
});
$("#menu_departamento").addClass('active');
buscar_departamento();
});
</script>
@endsection
@section('ruta_de_migas')
@endsection
@section('content')
<center><h1>{{ $page_title }}</h1></center>
<div class='row'>
  <div class='col-md-12'>
  <span id="txt_resultados">
</span>
 <div id="area_pagination"></div>
    
    
  </div><!-- /.col -->
  <div class='col-md-6'>

  </div><!-- /.col -->

</div><!-- /.row -->
@endsection