routes/web.php
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->rol = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);
Route::get('modo_escritorio/{id}',[
        'as'=>'modo_escritorio' ,
        'middleware' => 'auth',
        'uses' => function ($id) {
        $user = \App\User::find(Auth::user()->id);
        $user->modo_escritorio = $id;
        $user->save();
        return redirect()->back();//->to('home');
        }
    ]);

Route::group(['prefix' => 'admin', 'as'=>'admin.'], function () {
    Route::resources([
        'usuarios' => 'UserController'
    ]);
    Route::get('usuarios/{id}/delete',[
        'as'=>'usuarios.delete' ,
        'uses' => 'UserController@destroy'
    ]);
    Route::post('usuarios/{id}',[
        'as'=>'usuarios.update' ,
        'uses' => 'UserController@update'
    ]);
    
    
    Route::resources([
        'facultad' => 'FacController'
    ]);
    Route::get('facultad/{id}/delete',[
        'as'=>'facultad.delete' ,
        'uses' => 'FacController@destroy'
    ]);
    Route::post('facultad/{id}',[
        'as'=>'facultad.update' ,
        'uses' => 'FacController@update'
    ]);
    Route::resources([
        'periodo' => 'PeriodoController'
    ]);
    Route::get('periodo/{id}/delete',[
        'as'=>'periodo.delete' ,
        'uses' => 'PeriodoController@destroy'
    ]);
    Route::post('periodo/{id}',[
        'as'=>'periodo.update' ,
        'uses' => 'PeriodoController@update'
    ]);
    
     Route::resources([
        'departamento' => 'DeptoController'
    ]);
    Route::get('departamento/{id}/delete',[
        'as'=>'departamento.delete' ,
        'uses' => 'DeptoController@destroy'
    ]);
    Route::post('departamento/{id}',[
        'as'=>'departamento.update' ,
        'uses' => 'DeptoController@update'
    ]);
    
    Route::resources([
        'programa' => 'ProgController'
    ]);
    Route::get('programa/{id}/delete',[
        'as'=>'programa.delete' ,
        'uses' => 'ProgController@destroy'
    ]);
    Route::post('programa/{id}',[
        'as'=>'programa.update' ,
        'uses' => 'ProgController@update'
    ]);
    Route::resources([
        'asignatura' => 'AsigtController'
    ]);
    Route::get('asignatura/{id}/delete',[
        'as'=>'asignatura.delete' ,
        'uses' => 'AsigtController@destroy'
    ]);
    Route::post('asignatura/{id}',[
        'as'=>'asignatura.update' ,
        'uses' => 'AsigtController@update'
    ]);
    Route::resources([
        'contenido' => 'ContAsigtController'
    ]);
    Route::get('contenido/{id}/delete',[
        'as'=>'contenido.delete' ,
        'uses' => 'ContAsigtController@destroy',
        'middleware' => 'rol:admin'
    ]);
    Route::get('contenido/{id}/create',[
        'as'=>'contenido.create' ,
        'uses' => 'ContAsigtController@create',
        'middleware' => 'rol:admin'
    ]);
    Route::post('contenido/{id}',[
        'as'=>'contenido.update' ,
        'uses' => 'ContAsigtController@update',
        'middleware' => 'rol:admin'
    ]);
    Route::group(['prefix' => 'asignacion', 
    'as'=>'asignacion.'], function () {
        Route::resources([
            'programaciontematica' => 'ProgTemController'
        ]);
        Route::post('consultar_planes_prog',[
        'as'=>'consultar_planes_prog',
        'uses' => 'AsigcController@consultar_planes_prog'
        ]);
        Route::post('{id}/programaciontematica/update',[
        'as'=>'programaciontematica.update',
        'uses' => 'ProgTemController@update'
        ]);
          Route::group(['prefix' => 'programaciontematica', 'as'=>'programaciontematica.'], function () {
               Route::get('{id}/refebiblio/{id2}/delete',[
                'as'=>'refebiblio.delete' ,
                'uses' => 'ProgTemRefeBiblioController@destroy'
                ]);
                Route::post('{id}/refebiblio/store',[
                'as'=>'refebiblio.store' ,
                'uses' => 'ProgTemRefeBiblioController@store'
                ]);
                
               Route::get('{id}/puntoadic/{id2}/delete',[
                'as'=>'puntoadic.delete' ,
                'uses' => 'ProgTemPuntoAdicController@destroy'
                ]);
                Route::post('{id}/puntoadic/store',[
                'as'=>'puntoadic.store' ,
                'uses' => 'ProgTemPuntoAdicController@store'
                ]);
          });
        Route::resources([
            'seguimiento' => 'SegController'
        ]); 
        
    Route::post('seguimiento/{id}/edit',[
        'as'=>'seguimiento.edit' ,
        'uses' => 'SegController@edit_post'
    ]);

    
    Route::resources([
            'informefinal' => 'InfoFinController'
        ]);
    });
    Route::resources([
        'asignacion' => 'AsigcController'
    ]);
    Route::get('asignacion/{id}/delete',[
        'as'=>'asignacion.delete' ,
        'uses' => 'AsigcController@destroy'
    ]);
    Route::post('asignacion/{id}',[
        'as'=>'asignacion.update' ,
        'uses' => 'AsigcController@update'
    ]);
   Route::get('asignacion/create/individual',[
        'as'=>'asignacion.createindividual' ,
        'uses' => 'AsigcController@create_individual',
        'middleware' => 'rol:admin|director'
    ]);
   Route::get('asignacion/create/plan',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
  /*
   Route::get('asignacion/create/plan/{cod_prog}',[
        'as'=>'asignacion.createplan' ,
        'uses' => 'AsigcController@create_plan',
        'middleware' => 'rol:admin|director'
    ]);
*/
    Route::resources([
        'planes' => 'PlanesController'
    ]);
    Route::get('planes/{id}/delete',[
        'as'=>'planes.delete' ,
        'uses' => 'PlanesController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::post('planes/{id}',[
        'as'=>'planes.update' ,
        'uses' => 'PlanesController@update',
        'middleware' => 'rol:admin|director'
    ]);
    Route::get('planes/{id}/create',[
        'as'=>'planes.create' ,
        'uses' => 'PlanesController@create'
    ]);
  /*
  Route::put('post/{id}', ['middleware' => 'role:editor', function ($id) {
    //
}]);
  */
  
    Route::group(['prefix' => 'planes', 
    'as'=>'planes.'], function () {
        
        /*
        Route::get('{id}/asigt/create',[
        'as'=>'asigt.create' ,
        'uses' => 'PlanesAsigtController@create',
        'middleware' => 'rol:admin'
        ]);
        */
    });
  Route::get('planesasigt/{id}/delete',[
        'as'=>'planesasigt.delete' ,
        'uses' => 'PlanesAsigtController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::resources([
          'planesasigt' => 'PlanesAsigtController'
        ]);
    Route::resources([
          'planesasigtpre' => 'PlanesPreReqController'
        ]);
   Route::get('/planesasigtpre/{planes_id}/delete/{id}',[
        'as'=>'planesasigtpre.delete' ,
        'uses' => 'PlanesPreReqController@destroy',
        'middleware' => 'rol:admin|director'
    ]);
    Route::resources([
        'control' => 'ControlFechasController'
    ]);
    Route::get('control/{id}/delete',[
        'as'=>'control.delete' ,
        'uses' => 'ControlFechasController@destroy'
    ]);
    Route::post('control/{id}',[
        'as'=>'control.update' ,
        'uses' => 'ControlFechasController@update'
    ]);
    
    Route::resources([
        'links' => 'LinksController'
    ]);
    Route::get('links/{id}/delete',[
        'as'=>'links.delete' ,
        'uses' => 'LinksController@destroy'
    ]);
    Route::post('links/{id}',[
        'as'=>'links.update' ,
        'uses' => 'LinksController@update'
    ]);
    
    Route::resources([
        'programacion' => 'ProgTemController'
    ]);
    Route::get('programacion/{id}/delete',[
        'as'=>'programacion.delete' ,
        'uses' => 'ProgTemController@destroy'
    ]);
    Route::post('programacion/{id}',[
        'as'=>'programacion.update' ,
        'uses' => 'ProgTemController@update'
    ]);
    Route::resources([
        'seguimieto' => 'SegController'
    ]);
    Route::get('seguimieto/{id}/delete',[
        'as'=>'seguimieto.delete' ,
        'uses' => 'SegController@destroy'
    ]);
    Route::get('seguimieto/seguimieto/{id}',[
        'as'=>'seguimieto.update' ,
        'uses' => 'SegController@update'
    ]);
    Route::post('seguimieto/guardar_item/{id}/{id_asigc}',[
        'as'=>'seguimieto.guardar_item' ,
        'uses' => 'SegController@guardar_item'
    ]);
    Route::post('seguimieto/actualizar_item/{id}',[
        'as'=>'seguimieto.actualizar_item' ,
        'uses' => 'SegController@actualizar_item'
    ]);
    Route::post('seguimieto/eliminar_item/{id}',[
        'as'=>'seguimieto.eliminar_item' ,
        'uses' => 'SegController@eliminar_item'
    ]);
    Route::post('seguimieto/guardar_voto',[
        'as'=>'seguimieto.guardar_voto' ,
        'uses' => 'SegController@guardar_voto'
    ]);
    Route::resources([
        'informefinal' => 'InfoFinController'
    ]);
    Route::get('informefinal/{id}/delete',[
        'as'=>'informefinal.delete' ,
        'uses' => 'InfoFinController@destroy'
    ]);
    Route::post('informefinal/{id}',[
        'as'=>'informefinal.update' ,
        'uses' => 'InfoFinController@update'
    ]);
    Route::resources([
        'codigos' => 'CodigosController'
    ]);
    Route::get('codigos/{id}/create',[
        'as'=>'codigos.create' ,
        'uses' => 'CodigosController@create'
    ]);
    Route::get('codigos/{id}/delete',[
        'as'=>'codigos.delete' ,
        'uses' => 'CodigosController@destroy'
    ]);
    Route::post('codigos/{id}',[
        'as'=>'codigos.update' ,
        'uses' => 'CodigosController@update'
    ]);
});

Route::group(['prefix' => 'reportes', 'as'=>'reportes.'], function () {

app/Planes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Planes extends Model
{
    public $timestamps = false;
    protected $table = 'planes';
    protected $fillable = [
        'nombre',
        'adjunto',
        'fecha',
        'cod_prog',
        'observaciones'
    ];

    public $fillcolumn = [
        'nombre'=>'Nombre',
        'adjunto'=>'Adjunto',
        'fecha'=>'Fecha',
        'cod_prog' => 'Programa',
        'observaciones' => 'Observaciones'
    ];
  public function prog()
    {//Verificado
        return $this->belongsTo('App\Prog','cod_prog','cod_prog');
    }
 public function planes_asigts()
    {//Verificado
        return $this->hasMany('App\PlanesAsigt');
    }
 
}

resources/views/admin/planes/create.blade.php
@extends('layouts.app')
@section('vars')
{!!
$page_title = 'Planes'; 
$route = 'planes'; 
!!}
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li><a href="{{ route('admin.programa.index') }}"> Programa</a></li>
    <li><a href="{{ route('admin.programa.show',['id' => $prog->id]) }}">Detalles {{ $prog->nom_prog }}</a></li>
    <li class="active"> Registrar Plan</li>
</ol>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        password_en_formulario("admin_planes_create");
    required_en_formulario_for("admin_planes_create","red","*")
    });
    </script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"></div>

                <div class="card-body">
                    <form method="POST" id="admin_planes_create" action="{{ route('admin.planes.store') }}"  enctype="multipart/form-data">
                         <meta name="csrf-token" content="{{ csrf_token() }}">
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">

                       <div class="form-group row">
                            <label for="programa" class="col-md-4 col-form-label text-md-right">Programa</label>
                             <div class="col-md-6">
                            <label id="programa" lass="form-control">{{ $prog->nom_prog }} ({{ $prog->cod_prog }})</label>
                            <input name="cod_prog" type="hidden" value="{{ $prog->cod_prog }}">
                             </div>
                       </div>
                       <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ old('nombre') }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                       <div class="form-group row">
                            <label for="adjunto" class="col-md-4 col-form-label text-md-right">{{ __('Acuerdo') }}</label>

                            <div class="col-md-6">
                                <input id="adjunto" type="file" accept="application/pdf"  class="form-control{{ $errors->has('adjunto') ? ' is-invalid' : '' }}" name="adjunto" value="{{ old('adjunto') }}" required autofocus>

                                @if ($errors->has('adjunto'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('adjunto') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       <div class="form-group row">
                            <label for="fecha" class="col-md-4 col-form-label text-md-right">{{ __('Fecha') }}</label>

                            <div class="col-md-6">
                                <input id="fecha" type="date" class="form-control{{ $errors->has('fecha') ? ' is-invalid' : date('Y-m-d') }}" name="fecha" value="{{ old('fecha') }}" required autofocus>

                                @if ($errors->has('fecha'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('fecha') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       <div class="form-group row">
                         <div class="col-md-12">
                         <input type="hidden" name="asigt_plan" value="NO">
                            <input {{ old('asigt_plan')=='SI' ? ' checked ': '' }} id="asigt_plan" type="checkbox" class="" name="asigt_plan" value="SI">
                            <label for="asigt_plan" class="">{{ __('Continuar con asignaturas del plan') }}</label>
                             
                           
                                @if ($errors->has('asigt_plan'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('asigt_plan') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
<div class="form-group row">
    <label for="observaciones" class="col-md-4 col-form-label text-md-right">{{ __('Observaciones') }}</label>

    <div class="col-md-6">
        <input id="observaciones" type="text" class="form-control{{ $errors->has('observaciones') ? ' is-invalid' : '' }}" name="observaciones" value="{{ old('observaciones') }}" >

        @if ($errors->has('observaciones'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('observaciones') }}</strong>
            </span>
        @endif
    </div>
</div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
<a href="{{ route('admin.planes.index') }}" class="btn btn-secondary hidden-print">Regresar</a>
<input type="submit" name="submit" value="Registrar" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/planes/editar.blade.php
@extends('layouts.app')
@section('vars')
{!!
$page_title = 'planes'; 
$route = 'planes'; 
!!}
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li><a href="{{ route('admin.programa.index') }}"> Programa</a></li>
    <li><a href="{{ route('admin.programa.show',['id' => $planes->prog->id]) }}">Detalles {{ $planes->prog->nom_prog }}</a></li>
    <li class="active"> Modificar plan</li>
</ol>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        password_en_formulario("admin_planes_create");
    required_en_formulario_for("admin_planes_create","red","*")
    });
    </script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"></div>

                <div class="card-body">
                    <form method="POST" id="admin_planes_update" action="{{ route('admin.planes.update',[$planes->id]) }}"  enctype="multipart/form-data">
                         <meta name="csrf-token" content="{{ csrf_token() }}">
                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                         <input type="hidden" name="id" value="{{ $planes->id }}">

       <div class="form-group row">
            <label for="programa" class="col-md-4 col-form-label text-md-right">Programa</label>
             <div class="col-md-6">
            <label id="programa" lass="form-control">{{ $planes->prog->nom_prog }} ({{ $planes->prog->cod_prog }})</label>
            <input name="cod_prog" type="hidden" value="{{ $planes->prog->cod_prog }}">
             </div>
       </div>
       <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">{{ __('Nombre') }}</label>

            <div class="col-md-6">
<input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" required autofocus value="{{ count($errors)>0 ?  old('nombre') : $planes->nombre }}">

                @if ($errors->has('nombre'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('nombre') }}</strong>
                    </span>
                @endif
            </div>
        </div>
                      
                       <div class="form-group row">
                         <div class="col-md-4 ">
                            <label for="adjunto" class="col-form-label text-md-right">{{ __('Acuerdo') }}</label>
                           <br>
 <input type="hidden" name="modificar_adjunto" value="NO">
                            <input type="checkbox" class="" id="modificar_adjunto"  name="modificar_adjunto" value="SI" onclick="if(this.checked){
document.getElementById('adjunto_anterior').style.display = 'none';    
document.getElementById('adjunto_nuevo').style.display = 'initial';
document.getElementById('adjunto').setAttribute('required','required');
}else{
document.getElementById('adjunto_anterior').style.display = 'initial';
document.getElementById('adjunto_nuevo').style.display = 'none';                                         
document.getElementById('adjunto').removeAttribute('required');
}">
                            <label for="modificar_adjunto" class="">{{ __('Cambiar adjunto') }}</label>
                           </div>
                            <div class="col-md-6">
                              <span id="adjunto_anterior">
                              <a href="<?php echo env('APP_URL').$planes->adjunto ?>" target="_blank" style="color: red;font-size: large;"><span class="glyphicon glyphicon-paperclip"></span> Acuerdo</a>
                              </span>
                              <span id="adjunto_nuevo" style="display:none">
                                <input id="adjunto" type="file" accept="application/pdf"  class="form-control{{ $errors->has('adjunto') ? ' is-invalid' : '' }}" name="adjunto" value="{{ old('adjunto') }}" autofocus>
                              </span>
                                @if ($errors->has('adjunto'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('adjunto') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
<div class="form-group row">
    <label for="fecha" class="col-md-4 col-form-label text-md-right">{{ __('Fecha') }}</label>
  <div class="col-md-6">
      <input id="fecha" type="date" class="form-control{{ $errors->has('fecha') ? ' is-invalid' : date('Y-m-d') }}" name="fecha" value="{{ count($errors)>0 ?  old('fecha') : $planes->fecha }}" required autofocus>

      @if ($errors->has('fecha'))
          <span class="invalid-feedback">
              <strong>{{ $errors->first('fecha') }}</strong>
          </span>
      @endif
  </div>
</div>
<div class="form-group row">
    <label for="observaciones" class="col-md-4 col-form-label text-md-right">{{ __('Observaciones') }}</label>
    <div class="col-md-6">
        <input id="observaciones" type="text" class="form-control{{ $errors->has('observaciones') ? ' is-invalid' : '' }}" name="observaciones" value="{{ count($errors)>0 ?  old('observaciones') : $planes->observaciones }}" required>
        @if ($errors->has('observaciones'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('observaciones') }}</strong>
            </span>
        @endif
    </div>
</div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <div class="col-md-6 offset-md-4">
                                  
<a href="{{ route('admin.planes.index') }}" class="btn btn-secondary hidden-print">Regresar</a>
                                    <input type="submit" name="submit" value="Actualizar" class="btn btn-primary">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/planes/index.blade.php
@extends('layouts.app')
@section('vars')
{!! $page_title = 'Planes'; 
!!}
@endsection
@section('barra_buscar_cuerpo')
<nav class="navbar navbar-default">

<div >
 
                    <!-- Left Side Of Navbar -->
<ul class="nav navbar-nav navbar-right" style="margin-right: 0px;">
  <li><a style="margin: 0; padding: 8px;">
    <div class="input-group sidebar-form">
    <label for="buscar">Buscar por programa&nbsp;</label><br>
    <select style="background-color: #FFF;color:black;width:170px;display:inline" id="buscar_programa" name="cod_prog" class="js-example-basic-single form-control input_buscar">
      @foreach ($prog as $id => $prog_i)
      @if(Funciones::permiso_depto('cod_prog',$prog_i->cod_prog))
      <option @if($prog_i->cod_prog=="011") selected @endif value="{{$prog_i->cod_prog}}">{{$prog_i->nom_prog}}</option>
       @endif
      @endforeach
    </select>
    </div>
    </a></li>
    <li>
    <a> <input type="hidden" id="buscar" class="form-control" style="">
    <input type="hidden" id="buscar_arreglo" value="SI">
    <input type="hidden" name="flex" class="input_buscar2" value="SI">
    </a></li>
    <li>
      <div class="input-group sidebar-form">
          <label for="num_resultados">Resultados&nbsp;</label><br>
          <span class="input-group-btn" style="display:inline">
          <input title="Número de resultados" class="form-control" style="height: 27px;
    margin-top: 9px;background-color: rgb(255, 255, 255);color: black;width: 70px;border-bottom: 1px none transparent;border-left: 0px solid black;margin-right: 1px;border-right: 1px solid #ccd0d2;border-bottom: 1px solid #ccd0d2;background-color: #fff;
    border: 1px solid #aaa;
    border-radius: 4px;" min="1" id="num_resultados" name="num_resultados"  type="number" value="<?php 
    if (isset($_POST['num_resultados'])){
      echo $_POST['num_resultados'];
    }else{
      echo 3;
    }
    ?>" solonumeros>
          </span>
      </div>
    </li>
    <li style="
    margin: 0px;
    padding: 5px;
">
    </li>
</ul>
</div>
</nav>
@endsection
@section('scripts')
<script>
function preparar_buscar_planes(){
  var contenido = '{';
  var cont = 0;
  var total = $(".input_buscar").length;
  $(".input_buscar").each(function( index ) {
        $(this).each(function( index2 ) {
          contenido += '"'+this.name+'":"'+$(this).val()+'"';
          cont++;
          if(cont != total) contenido += ',';
        });
    });
    contenido += '}'
  $("#buscar").val(btoa(contenido));
  
}
$(document).ready(function(){
$(".input_buscar").keyup(function(){
  preparar_buscar_planes();
  buscar_planes();
});
$(".input_buscar").change(function(){
  preparar_buscar_planes();
  buscar_planes();
});
  preparar_buscar_planes();
  buscar_planes();
$("#buscar").keyup(function(){
  buscar_planes();
});
$("#buscar").change(function(){
  buscar_planes();
});
$("#search-btn").click(function(){
  buscar_planes();
});
$("#num_resultados").keyup(function(){
  buscar_planes();
});
$("#num_resultados").change(function(){
  buscar_planes();
});
$("#menu_configuraciones").addClass('active');
buscar_planes();
});
</script>
@endsection
@section('ruta_de_migas')
<ol class="breadcrumb">
    <li><a href="{{ route('home') }}"> Inicio</a></li>
    <li class="active"> {{ $page_title }}</li>
</ol>
@endsection
@section('content')
<center><h1>{{ $page_title }}</h1></center>
@if($botones)
<input type="hidden" id="a5d546a503db8d" value="{{ $botones ? __('true') : __('false') }}">
@endif
<div class='row'>
  <div class='col-md-12'>
  <span id="txt_resultados">
</span>
 <div id="area_pagination"></div>
    
    
  </div><!-- /.col -->
  <div class='col-md-6'>

  </div><!-- /.col -->

</div><!-- /.row -->
@endsection